
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shoumikbarmanpolok
 */
public class AGENT extends javax.swing.JFrame {

    /**
     * Creates new form AGENT
     */
    
     
        
    
    public AGENT() throws SQLException {
       // jLabel10 = new javax.swing.JLabel();
      
        
         Border pannel_border=BorderFactory.createMatteBorder(0,0,4,0,Color.white);
        // jLabel10.setBorder(pannel_border);
        
        initComponents();
        fillJtableWithOwnerData();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    
     public void fillJtableWithOwnerData() throws SQLException
    {
        P_REGISTER agent=new P_REGISTER();
        ArrayList<P_REGISTER> ownerList=agent.agentList();
        String[] colNames={"ID","First Name","Last Name","Username","Phone","Address"};
        Object[][] rows=new Object[ownerList.size()][6];
        for(int i=0;i<ownerList.size();i++)
        {
            rows[i][0]=ownerList.get(i).getId();
            rows[i][1]=ownerList.get(i).getFirstname();
            rows[i][2]=ownerList.get(i).getLastname();
            rows[i][4]=ownerList.get(i).getPhone();
            rows[i][3]=ownerList.get(i).getEmail();
            rows[i][5]=ownerList.get(i).getAddress();
            
        }
        DefaultTableModel model=new DefaultTableModel(rows,colNames);
        jTable_agent.setModel(model);
        jTable_agent.setRowHeight(40);
        jTable_agent.setSelectionBackground(Color.black);
        jTable_agent.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable_agent.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTable_agent.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_first = new javax.swing.JTextField();
        jTextField_last = new javax.swing.JTextField();
        jTextField_user = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jButton_edit = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_agent = new javax.swing.JTable();
        jButton_refresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jButton_password = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("            ID :");

        jTextField_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("First Name :");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Last Name :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Username :");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("      Phone :");

        jTextField_first.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jTextField_last.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jTextField_user.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jTextField_phone.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jButton_edit.setBackground(new java.awt.Color(51, 51, 255));
        jButton_edit.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(204, 0, 0));
        jButton_delete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jTable_agent.setBackground(new java.awt.Color(255, 153, 255));
        jTable_agent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTable_agent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_agent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_agentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_agent);

        jButton_refresh.setBackground(new java.awt.Color(255, 255, 0));
        jButton_refresh.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton_refresh.setText("Refresh");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("Password :");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("Agents:");

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel10.setText("Agents Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(522, 522, 522)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setText("   Address :");

        jTextArea_address.setColumns(20);
        jTextArea_address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextArea_address.setRows(5);
        jScrollPane3.setViewportView(jTextArea_address);

        jButton_password.setBackground(new java.awt.Color(255, 0, 204));
        jButton_password.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton_password.setText("Change Password");
        jButton_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_first)
                            .addComponent(jTextField_last)
                            .addComponent(jTextField_user)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_phone)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_password)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_first, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_last, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        String password=String.valueOf(jPasswordField1.getPassword());
        try{
        int owner_id=Integer.valueOf(jTextField_id.getText());
        P_REGISTER owner=new P_REGISTER();
        if(jTextField_id.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter The Agent Name","Empty Id",2);
        }
        else
        {
            if(password.equals(new P_REGISTER().getPasswordById(1))){
             int yes_or_no=JOptionPane.showConfirmDialog(null,"Do you want to delete this Agent","Delete Owner",JOptionPane.YES_NO_OPTION);
             if(yes_or_no==JOptionPane.YES_OPTION)
             {
                    if(owner.deleteAgent(owner_id))
                         {
                              JOptionPane.showMessageDialog(null,"Agent Deleted","Delete Agent",1);
                              jTextField_id.setText("");
                              jTextField_first.setText("");
                              jTextField_last.setText("");
                              jTextField_user.setText("");
                              jTextField_phone.setText("");
                              jTextArea_address.setText("");
                              jPasswordField1.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Operation Failed","Delete Agent",2);
                } 
                         
             }
        }
            else
            {
                 JOptionPane.showMessageDialog(null,"Admin Password Incorrect","Delete Agent",2);
            }
        }
        }catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null,"Enter Valid Data","Delete Agent",2);
                    }
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTable_agentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_agentMouseClicked
        // TODO add your handling code here:
         int selectedRowIndex=jTable_agent.getSelectedRow();
        int i=(int) jTable_agent.getValueAt(selectedRowIndex,0);
        if(i!=1){
        jTextField_id.setText(jTable_agent.getValueAt(selectedRowIndex,0).toString());
        jTextField_first.setText(jTable_agent.getValueAt(selectedRowIndex,1).toString());
        jTextField_last.setText(jTable_agent.getValueAt(selectedRowIndex,2).toString());
        jTextField_phone.setText(jTable_agent.getValueAt(selectedRowIndex,4).toString());
        jTextField_user.setText(jTable_agent.getValueAt(selectedRowIndex,3).toString());
        jTextArea_address.setText(jTable_agent.getValueAt(selectedRowIndex,5).toString());
        }
    }//GEN-LAST:event_jTable_agentMouseClicked

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
                                fillJtableWithOwnerData();
                                jTextField_id.setText("");
                              jTextField_first.setText("");
                              jTextField_last.setText("");
                              jTextField_user.setText("");
                              jTextField_phone.setText("");
                              jTextArea_address.setText("");
                              jPasswordField1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(OWNER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
       String fname=jTextField_first.getText();
       String lname=jTextField_last.getText();
       String phone=jTextField_phone.getText();
       String email=jTextField_user.getText();
       String address=jTextArea_address.getText();
       String password=String.valueOf(jPasswordField1.getPassword());
       P_REGISTER owner=new P_REGISTER();
        try{
            
            int ownerId=Integer.valueOf(jTextField_id.getText());
            
            if(fname.trim().equals("") || lname.trim().equals("")||phone.trim().equals("")||email.trim().equals("")||address.trim().equals("")||password.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Enter The Agent Information First ","Edit Agent",1);
            }
        else{
               if(password.equals(new P_REGISTER().getPasswordById(ownerId))){
            if(owner.editAgentData(new P_REGISTER(ownerId,fname,lname,email,password,phone,address)))
            {
                JOptionPane.showMessageDialog(null,"New Agent Data Edited To The System","Edit Agent",1);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Agent Data NOT Edited To The System","Edit Agent",2);
            }
       
            }
               else
            {
                    JOptionPane.showMessageDialog(null,"Incorrect Password","Edit Agent Data",2);
           
             }
            }
            
        }catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null,"Enter Valid Data","Edit Owner",2);
                    }
                   
        
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_passwordActionPerformed
        // TODO add your handling code here:
         int agentId=Integer.valueOf(jTextField_id.getText());
         String fname=jTextField_first.getText();
       String lname=jTextField_last.getText();
       String phone=jTextField_phone.getText();
       String email=jTextField_user.getText();
       String address=jTextArea_address.getText();
         
          PASSWORD_CHANGE clientform = null;
                    clientform = new PASSWORD_CHANGE(agentId,fname,lname,phone,email,address);
                    clientform.setVisible(true);
                    clientform.pack();
                    clientform.setLocationRelativeTo(null);
                    clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AGENT().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AGENT.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_password;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_agent;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextField jTextField_first;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_last;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_user;
    // End of variables declaration//GEN-END:variables

   
}
