
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shoumikbarmanpolok
 */
public class ALL_DETAILS extends javax.swing.JFrame {

    /**
     * Creates new form ALL_DETAILS
     */
    public ALL_DETAILS() throws SQLException {
        initComponents();
        fillJtableClients();
        setLocationRelativeTo(null);
         getContentPane().setBackground(new java.awt.Color(128, 0, 128)); // Set background color to purple
        //  private Timer timer;
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTotal();
            }
        });
        timer.start();

    }
    public void fillJtableClients() throws SQLException
    {
        
        int a,b,c,d,e;
         P_CLIENT client=new P_CLIENT();
        ArrayList<P_CLIENT> clientList=client.clientList();
        a=clientList.size();
        
          P_PROPERTY property=new P_PROPERTY();
        ArrayList<P_PROPERTY> propertyList=property.propertiesList();
        b=propertyList.size();
        
         P_SALES sale=new P_SALES();
        ArrayList<P_SALES> saleList=sale.clientList();
        c=saleList.size();
        
         P_REGISTER agent=new P_REGISTER();
        ArrayList<P_REGISTER> agentlist=agent.agentList();
        d=agentlist.size();
        
          P_OWNER owner=new P_OWNER();
        ArrayList<P_OWNER> ownerList=owner.ownerList();
        e=ownerList.size();
        
        String[] colNames={"Name","Total"};
        
        Object[][] rows=new Object[5][2];
       
            rows[0][0]="Agent";
            rows[0][1]=d;
            
             rows[1][0]="Owner";
            rows[1][1]=e;
            
             rows[2][0]="Client";
            rows[2][1]=a;
            
             rows[3][0]="Property";
            rows[3][1]=b;
            
             rows[4][0]="Sale";
            rows[4][1]=c;
   
        
        DefaultTableModel model=new DefaultTableModel(rows,colNames);
        jTable1.setModel(model);
          jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(Color.black);
        

    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 255));
        setResizable(false);

        jTable1.setBackground(new java.awt.Color(255, 51, 51));
        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Total Income");

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
                                           
  /*  P_SALES sale = new P_SALES();
    
    try {
        ArrayList<P_SALES> saleList = sale.clientList();
        long total = 0;

        for (int i = 0; i < saleList.size(); i++) {
            String price = saleList.get(i).getFinalPrice();
            long y = Long.valueOf(price);
            total += y;

            final long currentTotal = total; // Make it final to use inside the invokeLater

            SwingUtilities.invokeLater(() -> {
                jTextField1.setText(String.valueOf(currentTotal));
            });
        }
    } catch (SQLException ex) {
        Logger.getLogger(ALL_DETAILS.class.getName()).log(Level.SEVERE, null, ex);
    }
*/
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1FocusLost
      private void updateTotal() {
        P_SALES sale = new P_SALES();

        try {
            ArrayList<P_SALES> saleList = sale.clientList();
            long total = 0;

            for (int i = 0; i < saleList.size(); i++) {
                String price = saleList.get(i).getFinalPrice();
                long y = Long.valueOf(price);
                total += y;
            }

            jTextField1.setText(String.valueOf(total));
        } catch (SQLException ex) {
            Logger.getLogger(ALL_DETAILS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALL_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALL_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALL_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALL_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ALL_DETAILS().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ALL_DETAILS.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
