
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shoumikbarmanpolok
 * 1.ALTER TABLE the_property 
ADD CONSTRAINT fk_type_id 
FOREIGN KEY (type) 
REFERENCES property_type (id) 
ON UPDATE CASCADE 
ON DELETE CASCADE;

 * 
 * 
 * 2.ALTER TABLE `the_property`
ADD CONSTRAINT `fk_owner_id`
FOREIGN KEY (`ownerId`)
REFERENCES `property_own` (`id`)
ON UPDATE CASCADE
ON DELETE CASCADE;

 * 
 *3. ALTER TABLE `property-images` ADD CONSTRAINT `fk_property_id` FOREIGN KEY (`property_id`) REFERENCES `the_property` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
 * 
 * 4.ALTER TABLE sale
ADD CONSTRAINT fk_property_id_new
FOREIGN KEY (property_id)
REFERENCES the_property (id)
ON UPDATE CASCADE
ON DELETE CASCADE;

* 
* 
* 5.
 */
public class MAIN_APP extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_APP
     */
    
    
    
    public MAIN_APP() {
        initComponents();
        Border appname_border=BorderFactory.createMatteBorder(0,0,4,0,Color.black);
        jLabel_APP_Name.setBorder(appname_border);
        
         Border prperty_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_Property.setBorder(prperty_border);
        
         Border image_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_Image.setBorder(image_border);
        
         Border menuItem_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_Propertytype.setBorder(menuItem_border);
        
         Border Owner_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_Owner.setBorder(Owner_border);
        
         Border client_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_Client.setBorder(client_border);
        
        Border sales_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_sales.setBorder(sales_border);
        
        Border agent_border=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_sales1.setBorder(agent_border);
        
        Border agent_border2=BorderFactory.createMatteBorder(0,0,2,0,Color.black);
        jLabel_sales2.setBorder(agent_border2);
       // Add components to the center of jPanel2

// For example, add jButton1 to the south of jPanel2:
        jPanel2.add(jButton1, java.awt.BorderLayout.SOUTH);
        
       // this.setLocationRelativeTo(null);
       
       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("tenor (2) (3).gif")));
        
        
    }
    
     public ImageIcon resizeImage(String path, byte[] byteImage) {
        ImageIcon pic;
        if (byteImage != null) pic = new ImageIcon(byteImage);
        else pic = new ImageIcon(path);

        Image img = pic.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        return image;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_APP_Name = new javax.swing.JLabel();
        jLabel_Propertytype = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();
        jLabel_Owner = new javax.swing.JLabel();
        jLabel_Property = new javax.swing.JLabel();
        jLabel_Client = new javax.swing.JLabel();
        jLabel_sales = new javax.swing.JLabel();
        jLabel_sales1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_sales2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel_APP_Name.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_APP_Name.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel_APP_Name.setText("My Property");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel_APP_Name)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel_APP_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel_Propertytype.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_Propertytype.setText("Property-Type");
        jLabel_Propertytype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PropertytypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PropertytypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PropertytypeMouseExited(evt);
            }
        });

        jLabel_Image.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_Image.setText("Property-Images");
        jLabel_Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ImageMouseExited(evt);
            }
        });

        jLabel_Owner.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_Owner.setText("Owner");
        jLabel_Owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_OwnerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_OwnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_OwnerMouseExited(evt);
            }
        });

        jLabel_Property.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_Property.setText("Property");
        jLabel_Property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PropertyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PropertyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PropertyMouseExited(evt);
            }
        });

        jLabel_Client.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_Client.setText("Client");
        jLabel_Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ClientMouseExited(evt);
            }
        });

        jLabel_sales.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_sales.setText("Sales");
        jLabel_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_salesMouseExited(evt);
            }
        });

        jLabel_sales1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_sales1.setText("Agents");
        jLabel_sales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sales1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_sales1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_sales1MouseExited(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_sales2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_sales2.setText("DataSummary");
        jLabel_sales2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sales2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_sales2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_sales2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_sales2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sales1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Property, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Owner, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Propertytype, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel_Property, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Propertytype, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Owner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_sales1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_sales2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_PropertyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyMouseEntered
        // TODO add your handling code here:
        jLabel_Property.setBackground(Color.white);
        jLabel_Property.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_PropertyMouseEntered

    private void jLabel_PropertyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyMouseExited
        // TODO add your handling code here:
        jLabel_Property.setBackground(Color.darkGray);
        jLabel_Property.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_PropertyMouseExited

    private void jLabel_PropertytypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertytypeMouseEntered
        // TODO add your handling code here:
        jLabel_Propertytype.setBackground(Color.white);
        jLabel_Propertytype.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_PropertytypeMouseEntered

    private void jLabel_PropertytypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertytypeMouseExited
        // TODO add your handling code here:
        jLabel_Propertytype.setBackground(Color.darkGray);
        jLabel_Propertytype.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_PropertytypeMouseExited

    private void jLabel_ImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ImageMouseEntered
        // TODO add your handling code here:
        jLabel_Image.setBackground(Color.white);
        jLabel_Image.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_ImageMouseEntered

    private void jLabel_ImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ImageMouseExited
        // TODO add your handling code here:
        jLabel_Image.setBackground(Color.darkGray);
        jLabel_Image.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_ImageMouseExited

    private void jLabel_OwnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_OwnerMouseEntered
        // TODO add your handling code here:
        jLabel_Owner.setBackground(Color.white);
        jLabel_Owner.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_OwnerMouseEntered

    private void jLabel_OwnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_OwnerMouseExited
        // TODO add your handling code here:
        jLabel_Owner.setBackground(Color.darkGray);
        jLabel_Owner.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_OwnerMouseExited

    private void jLabel_ClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ClientMouseEntered
        // TODO add your handling code here:
        jLabel_Client.setBackground(Color.white);
        jLabel_Client.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_ClientMouseEntered

    private void jLabel_ClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ClientMouseExited
        // TODO add your handling code here:
        jLabel_Client.setBackground(Color.darkGray);
        jLabel_Client.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_ClientMouseExited

    private void jLabel_PropertytypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertytypeMouseClicked
        // TODO add your handling code here:
         // JOptionPane.showMessageDialog(null,"We need to show the Main form to the user");
                    PROPERTY_TYPE typeform=new PROPERTY_TYPE();
                   // this.setVisible(false);
                    typeform.setVisible(true);
                    typeform.pack();
                    typeform.setLocationRelativeTo(null);
                    typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_PropertytypeMouseClicked

    private void jLabel_OwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_OwnerMouseClicked
        // TODO add your handling code here:
                    OWNER ownerform = null;
        try {
            ownerform = new OWNER();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_APP.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // this.setVisible(false);
                    ownerform.setVisible(true);
                    ownerform.pack();
                    ownerform.setLocationRelativeTo(null);
                    ownerform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_OwnerMouseClicked

    private void jLabel_ClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ClientMouseClicked
        // TODO add your handling code here:
                 CLIENT clientform = null;
        try {
            clientform = new CLIENT();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_APP.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // this.setVisible(false);
                    clientform.setVisible(true);
                    clientform.pack();
                    clientform.setLocationRelativeTo(null);
                    clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_ClientMouseClicked

    private void jLabel_PropertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PropertyMouseClicked
        // TODO add your handling code here:
        
                  PROPERTY propertyform = null;
                  propertyform = new PROPERTY();
                   // this.setVisible(false);
                    propertyform.setVisible(true);
                    propertyform.pack();
                    propertyform.setLocationRelativeTo(null);
                    propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
    }//GEN-LAST:event_jLabel_PropertyMouseClicked

    private void jLabel_ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ImageMouseClicked
        // TODO add your handling code here:
        PROPERTY_IMAGE propertyform = null;
        try {
            propertyform = new PROPERTY_IMAGE();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_APP.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // this.setVisible(false);
                    propertyform.setVisible(true);
                    propertyform.pack();
                    propertyform.setLocationRelativeTo(null);
                    propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_ImageMouseClicked

    private void jLabel_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salesMouseClicked
        // TODO add your handling code here:
        SALES propertyform = null;
        try {
            propertyform = new SALES();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_APP.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // this.setVisible(false);
                    propertyform.setVisible(true);
                    propertyform.pack();
                    propertyform.setLocationRelativeTo(null);
                    propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_salesMouseClicked

    private void jLabel_salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salesMouseEntered
        // TODO add your handling code here:
        jLabel_sales.setBackground(Color.white);
        jLabel_sales.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_salesMouseEntered

    private void jLabel_salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salesMouseExited
        // TODO add your handling code here:
        jLabel_sales.setBackground(Color.darkGray);
        jLabel_sales.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_salesMouseExited

    private void jLabel_sales1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sales1MouseClicked
        // TODO add your handling code here:
        
        AGENT typeform=null;
        try {
            typeform = new AGENT();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_APP.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // this.setVisible(false);
                    typeform.setVisible(true);
                    typeform.pack();
                    typeform.setLocationRelativeTo(null);
                    typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_sales1MouseClicked

    private void jLabel_sales1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sales1MouseEntered
        // TODO add your handling code here:
        jLabel_sales1.setBackground(Color.white);
        jLabel_sales1.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_sales1MouseEntered

    private void jLabel_sales1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sales1MouseExited
        // TODO add your handling code here:
         jLabel_sales1.setBackground(Color.darkGray);
        jLabel_sales1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_sales1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LOGIN mainform=new LOGIN();
                   // this.setVisible(false);
                    mainform.setVisible(true);
                    mainform.pack();
                    mainform.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel_sales2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sales2MouseClicked
        // TODO add your handling code here:
         ALL_DETAILS typeform=null;
        try {
            typeform = new ALL_DETAILS();
        } catch (SQLException ex) {
            Logger.getLogger(MAIN_APP.class.getName()).log(Level.SEVERE, null, ex);
        }
                   // this.setVisible(false);
                    typeform.setVisible(true);
                    typeform.pack();
                    typeform.setLocationRelativeTo(null);
                    typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_sales2MouseClicked

    private void jLabel_sales2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sales2MouseEntered
        // TODO add your handling code here:
         jLabel_sales2.setBackground(Color.white);
        jLabel_sales2.setForeground( Color.darkGray);
    }//GEN-LAST:event_jLabel_sales2MouseEntered

    private void jLabel_sales2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sales2MouseExited
        // TODO add your handling code here:
         jLabel_sales2.setBackground(Color.darkGray);
        jLabel_sales2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_sales2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_APP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_APP_Name;
    private javax.swing.JLabel jLabel_Client;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Owner;
    private javax.swing.JLabel jLabel_Property;
    private javax.swing.JLabel jLabel_Propertytype;
    private javax.swing.JLabel jLabel_sales;
    private javax.swing.JLabel jLabel_sales1;
    private javax.swing.JLabel jLabel_sales2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
