/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author shoumikbarmanpolok
 */
public class PROPERTY extends javax.swing.JFrame {

    /**
     * Creates new form PROPERTY
     */
        P_TYPE type=new P_TYPE();
        HashMap<String,Integer> map=type.getTypesMap();
        
    public PROPERTY() {
        initComponents();
        Border pannel_border=BorderFactory.createMatteBorder(0,0,4,0,Color.white);
         jLabel_prtype.setBorder(pannel_border);
         
         bindCombo();
    }

    public void bindCombo()
    {
        
        for(String s : map.keySet())
        {
            jComboBox1.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_prtype = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jButton_edit = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_feet = new javax.swing.JTextField();
        jTextField_ownerId = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jSpinner_bed = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_bath = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_age = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jCheckBox_balcone = new javax.swing.JCheckBox();
        jCheckBox_pool = new javax.swing.JCheckBox();
        jCheckBox_garage = new javax.swing.JCheckBox();
        jCheckBox_backyard = new javax.swing.JCheckBox();
        jButton_show = new javax.swing.JButton();
        jButton_show1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel_prtype.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel_prtype.setText("Property");
        jLabel_prtype.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(502, 502, 502)
                .addComponent(jLabel_prtype, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_prtype, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("              ID:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("    Address:");

        jLabel_type.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel_type.setText("          Type:");

        jTextField_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jTextArea_address.setColumns(20);
        jTextArea_address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextArea_address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_address);

        jButton_edit.setBackground(new java.awt.Color(255, 51, 204));
        jButton_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_edit.setText("Edit");
        jButton_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_remove.setBackground(new java.awt.Color(0, 102, 102));
        jButton_remove.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_remove.setText("Remove");
        jButton_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jButton_add.setBackground(new java.awt.Color(0, 255, 51));
        jButton_add.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_add.setText("Add");
        jButton_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("  Square Feet :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Price(USD):");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText(" Owner Id:");

        jTextField_feet.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_feet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_feetActionPerformed(evt);
            }
        });

        jTextField_ownerId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_ownerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ownerIdActionPerformed(evt);
            }
        });

        jTextField_price.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_priceActionPerformed(evt);
            }
        });

        jButton_search.setBackground(new java.awt.Color(102, 102, 102));
        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("      Bathrooms:");

        jSpinner_bed.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("       Bedrooms:");

        jSpinner_bath.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("  Age of house:");

        jSpinner_age.setModel(new javax.swing.SpinnerNumberModel());

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setText("     Description:");

        jTextArea_description.setColumns(20);
        jTextArea_description.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextArea_description.setRows(5);
        jScrollPane2.setViewportView(jTextArea_description);

        jCheckBox_balcone.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jCheckBox_balcone.setText("Balcone");

        jCheckBox_pool.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jCheckBox_pool.setText("Pool");

        jCheckBox_garage.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jCheckBox_garage.setText("Garage");
        jCheckBox_garage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_garageActionPerformed(evt);
            }
        });

        jCheckBox_backyard.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jCheckBox_backyard.setText("Backyard");
        jCheckBox_backyard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_backyardActionPerformed(evt);
            }
        });

        jButton_show.setBackground(new java.awt.Color(204, 204, 0));
        jButton_show.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_show.setText("Show Properties");
        jButton_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showActionPerformed(evt);
            }
        });

        jButton_show1.setBackground(new java.awt.Color(51, 102, 255));
        jButton_show1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton_show1.setText("Refresh");
        jButton_show1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_type)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(3, 3, 3))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jTextField_feet, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jTextField_ownerId, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jTextField_price, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinner_bed, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSpinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSpinner_bath, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_pool, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_balcone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_garage, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_backyard, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton_show, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton_show1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_bed, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_balcone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_type, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_bath, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_pool, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_feet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_ownerId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox_backyard, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox_garage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_show, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_show1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        // int ownerId=Integer.valueOf(jTextField_id.getText());
       // String fname=jTextField_first.getText();
         try{
            int id=Integer.valueOf(jTextField_id.getText());
            int type=map.get(jComboBox1.getSelectedItem().toString());
            int ownerId=Integer.valueOf(jTextField_ownerId.getText());
            int squareFeet=Integer.valueOf(jTextField_feet.getText());
            int bedrooms=Integer.valueOf(jSpinner_bed.getValue().toString());
            int bathrooms=Integer.valueOf(jSpinner_bath.getValue().toString());
            int age=Integer.valueOf(jSpinner_age.getValue().toString());
          //  int type=Integer.valueOf(jComboBox1.getSelectedIndex());
            boolean haveBalcone=false;
            boolean havePool=false;
            boolean haveBackyard=false;
            boolean haveGarage=false;
            
            if(jCheckBox_balcone.isSelected()) haveBalcone=true;
            if(jCheckBox_pool.isSelected()) havePool=true;
            if(jCheckBox_backyard.isSelected()) haveBackyard=true;
            if(jCheckBox_garage.isSelected()) haveGarage=true;
            
          
            String price=jTextField_price.getText();
            String address=jTextArea_address.getText();
            String description=jTextArea_description.getText();
            
            P_PROPERTY property=new P_PROPERTY(id,type,squareFeet,ownerId,price,address,bedrooms,bathrooms,age,haveBalcone,havePool,haveBackyard,haveGarage,description);
            
            if(new P_PROPERTY().editNewProperty(property))
            {
                JOptionPane.showMessageDialog(null,"Property Edited","Edit Property",1);
                }
            else
            {
                    JOptionPane.showMessageDialog(null,"Property NOT Edited","EDit Property",2);
            }
                    
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage()+"Error","Error",2);
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // TODO add your handling code here:
         try{
            int id=Integer.valueOf(jTextField_id.getText());
            P_PROPERTY client=new P_PROPERTY();
            if(jTextField_id.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Enter The Property ID","Empty ID",2);
            }
            else
            {
                int yes_or_no=JOptionPane.showConfirmDialog(null,"Do you want to delete this Property","Delete Property",JOptionPane.YES_NO_OPTION);
                if(yes_or_no==JOptionPane.YES_OPTION)
                {
                    if(client.removeProperty(id))
                    {
                        JOptionPane.showMessageDialog(null,"Property Deleted","Delete Property",1);
                        jTextField_id.setText("");
                         jTextArea_address.setText("");
                 jTextArea_description.setText("");
                 jTextField_price.setText("");
                 jTextField_feet.setText("");
                 jTextField_ownerId.setText("");
                 jSpinner_bed.setValue(0);
                 jSpinner_bath.setValue(0);
                 jSpinner_age.setValue(0);
                // jComboBox1.setSelectedItem(map.get(property.getType()));
                
               
                        jComboBox1.setSelectedIndex(0);
                
                 
                 jCheckBox_backyard.setSelected(false);
                jCheckBox_balcone.setSelected(false);
                jCheckBox_pool.setSelected(false);
                jCheckBox_garage.setSelected(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Operation Failed","Delete Property",2);
                    }

                }
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data","Delete Property",2);
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        
        try{
            int type=map.get(jComboBox1.getSelectedItem().toString());
            int ownerId=Integer.valueOf(jTextField_ownerId.getText());
            int squareFeet=Integer.valueOf(jTextField_feet.getText());
            int bedrooms=Integer.valueOf(jSpinner_bed.getValue().toString());
            int bathrooms=Integer.valueOf(jSpinner_bath.getValue().toString());
            int age=Integer.valueOf(jSpinner_age.getValue().toString());
          //  int type=Integer.valueOf(jComboBox1.getSelectedIndex());
            boolean haveBalcone=false;
            boolean havePool=false;
            boolean haveBackyard=false;
            boolean haveGarage=false;
            
            if(jCheckBox_balcone.isSelected()) haveBalcone=true;
            if(jCheckBox_pool.isSelected()) havePool=true;
            if(jCheckBox_backyard.isSelected()) haveBackyard=true;
            if(jCheckBox_garage.isSelected()) haveGarage=true;
            
          
            String price=jTextField_price.getText();
            String address=jTextArea_address.getText();
            String description=jTextArea_description.getText();
            
            P_PROPERTY property=new P_PROPERTY(0,type,squareFeet,ownerId,price,address,bedrooms,bathrooms,age,haveBalcone,havePool,haveBackyard,haveGarage,description);
            
            if(new P_PROPERTY().addNewProperty(property))
            {
                JOptionPane.showMessageDialog(null,"New Property Added To The System","Add Property",1);
                }
            else
            {
                    JOptionPane.showMessageDialog(null,"Property NOT Added To The System","Add Property",2);
            }
                    
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage()+"Error","Error",2);
        }
        
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTextField_feetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_feetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_feetActionPerformed

    private void jTextField_ownerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ownerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ownerIdActionPerformed

    private void jTextField_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_priceActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // TODO add your handling code here:
        
        jCheckBox_backyard.setSelected(false);
        jCheckBox_balcone.setSelected(false);
        jCheckBox_pool.setSelected(false);
        jCheckBox_garage.setSelected(false);
        
        
        
        try{
            int propertyId=Integer.valueOf(jTextField_id.getText());
             P_PROPERTY property=new P_PROPERTY().findProperty(propertyId);
             
             if(property != null)
             {
                 jTextArea_address.setText(property.getAddress());
                 jTextArea_description.setText(property.getDescription());
                 jTextField_price.setText(property.getPrice());
                 jTextField_feet.setText(String.valueOf(property.getSize()));
                 jTextField_ownerId.setText(String.valueOf(property.getOwnerId()));
                 jSpinner_bed.setValue(property.getBedrooms());
                 jSpinner_bath.setValue(property.getBathrooms());
                 jSpinner_age.setValue(property.getAge());
                // jComboBox1.setSelectedItem(map.get(property.getType()));
                
               for (Object type : map.keySet()) {
    if (map.get(type).equals(property.getType())) {
        jComboBox1.setSelectedItem(type);
        break; // Break the loop once a match is found
    }
}

                 
                 if(property.isBackyard()) jCheckBox_backyard.setSelected(true);
                 if(property.isBalcone()) jCheckBox_balcone.setSelected(true);
                 if(property.isPool()) jCheckBox_pool.setSelected(true);
                 if(property.isGarage()) jCheckBox_garage.setSelected(true);
             }
             else
             {
                 JOptionPane.showMessageDialog(null,"Property Not Found","Error",2);
             }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage()+"Error","Error",2);
        }
        
        
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jCheckBox_backyardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_backyardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_backyardActionPerformed

    private void jCheckBox_garageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_garageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_garageActionPerformed

    private void jButton_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showActionPerformed
        // TODO add your handling code here:
                  SHOW_PROPERTY showPropertyform = null;
            try {
                showPropertyform = new SHOW_PROPERTY();
            } catch (SQLException ex) {
                Logger.getLogger(PROPERTY.class.getName()).log(Level.SEVERE, null, ex);
            }
                   // this.setVisible(false);
                    showPropertyform.setVisible(true);
                    showPropertyform.pack();
                    showPropertyform.setLocationRelativeTo(null);
                    showPropertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
    }//GEN-LAST:event_jButton_showActionPerformed

    private void jButton_show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show1ActionPerformed
        // TODO add your handling code here:
        
                             jTextField_price.setText("");
                              jTextField_id.setText("");
                              jTextField_ownerId.setText("");
                              jTextField_feet.setText("");
                              jTextArea_address.setText("");
                              jTextArea_description.setText("");
                              jCheckBox_backyard.setSelected(false);
        jCheckBox_balcone.setSelected(false);
        jCheckBox_pool.setSelected(false);
        jCheckBox_garage.setSelected(false);
        jComboBox1.setSelectedItem(null);
        jSpinner_bed.setValue(0);
                 jSpinner_bath.setValue(0);
                 jSpinner_age.setValue(0);
        
                              
    }//GEN-LAST:event_jButton_show1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROPERTY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_show;
    private javax.swing.JButton jButton_show1;
    private javax.swing.JCheckBox jCheckBox_backyard;
    private javax.swing.JCheckBox jCheckBox_balcone;
    private javax.swing.JCheckBox jCheckBox_garage;
    private javax.swing.JCheckBox jCheckBox_pool;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_prtype;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_age;
    private javax.swing.JSpinner jSpinner_bath;
    private javax.swing.JSpinner jSpinner_bed;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextField jTextField_feet;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_ownerId;
    private javax.swing.JTextField jTextField_price;
    // End of variables declaration//GEN-END:variables
}
