
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shoumikbarmanpolok
 */
public class SHOW_PROPERTY extends javax.swing.JFrame {

    /**
     * Creates new form SHOW_PROPERTY
     */
    public SHOW_PROPERTY() throws SQLException {
        initComponents();
        fillJtableWithPropertiesData();
       
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(Color.black);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
         jTable1.getColumnModel().getColumn(3).setPreferredWidth(45); 
         jTable1.getColumnModel().getColumn(1).setPreferredWidth(45);
          jTable1.getColumnModel().getColumn(8).setPreferredWidth(35);

    }
    public void fillJtableWithPropertiesData() throws SQLException
    {
        P_PROPERTY property=new P_PROPERTY();
        ArrayList<P_PROPERTY> propertyList=property.propertiesList();
        
        String[] colNames={"ID","Type","Square_Feet)", "OwnerId", "Price","Address", "Bedrooms", "Bathrooms", "Age", "Balcone", "Pool", "Backyard", "Garage", "Description","Status"};
        Object[][] rows=new Object[propertyList.size()][15];
        for(int i=0;i<propertyList.size();i++)
        {
            rows[i][0]=propertyList.get(i).getId();
            rows[i][1]=propertyList.get(i).getType();
            rows[i][2]=propertyList.get(i).getSize();
            rows[i][3]=propertyList.get(i).getOwnerId();
            rows[i][4]=propertyList.get(i).getPrice();
            rows[i][5]=propertyList.get(i).getAddress();
            rows[i][6]=propertyList.get(i).getBedrooms();
            rows[i][7]=propertyList.get(i).getBathrooms();
            rows[i][8]=propertyList.get(i).getAge();
            if(propertyList.get(i).isBalcone()) rows[i][9]="Yes";
            else
                rows[i][9]="No";
            
            if(propertyList.get(i).isPool()) rows[i][10]="Yes";
            else
                rows[i][10]="No";
            
            if(propertyList.get(i).isBackyard()) rows[i][11]="Yes";
            else
                rows[i][11]="No";
            
            if(propertyList.get(i).isGarage()) rows[i][12]="Yes";
            else
                rows[i][12]="No";
       
            rows[i][13]=propertyList.get(i).getDescription();
            
            if(new P_SALES().propertyIsNotSold(propertyList.get(i).getId()))
            {
                rows[i][14]="Available";
                
            }
            else
            {
                rows[i][14]="Sold";
            }
            
        }
        DefaultTableModel model=new DefaultTableModel(rows,colNames);
         jTable1.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jLabel_address = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextArea_address.setColumns(20);
        jTextArea_address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextArea_address.setRows(5);
        jScrollPane2.setViewportView(jTextArea_address);

        jTextArea_description.setColumns(20);
        jTextArea_description.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextArea_description.setRows(5);
        jScrollPane3.setViewportView(jTextArea_description);

        jLabel_address.setBackground(new java.awt.Color(102, 0, 0));
        jLabel_address.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel_address.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_address.setText("Address:");
        jLabel_address.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(102, 0, 0));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description:");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_address, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_address, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int selectedRowIndex=jTable1.getSelectedRow();
        jTextArea_address.setText(jTable1.getValueAt(selectedRowIndex,5).toString());
        jTextArea_description.setText(jTable1.getValueAt(selectedRowIndex,13).toString());
        
        
        /////
        try{
            
               int rowIndex=jTable1.getSelectedRow();
       int id=Integer.valueOf(jTable1.getValueAt(rowIndex,0).toString());
       PROPERTY_IMAGES_SLIDER clientform = null;
      // clientform = new PROPERTY_IMAGES_SLIDER(id);
       
       
      // clientform.propertyId=id;
                   // this.setVisible(false);
                   
                   
                   clientform = new PROPERTY_IMAGES_SLIDER(id);
                    clientform.setVisible(true);
                    clientform.pack();
                    clientform.setLocationRelativeTo(null);
                    clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                   
                   
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Selected property","Select Property",2);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOW_PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOW_PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOW_PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOW_PROPERTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SHOW_PROPERTY().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SHOW_PROPERTY.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextArea jTextArea_description;
    // End of variables declaration//GEN-END:variables
}
